/** @file city_file.cpp
 *
 * File created by Peter Watkins (KE7IST) 1/9/18.
 * Derived from original project code.
 * Splat!
 * @copyright 1997 - 2018 John A. Magliacane (KD2BD) and contributors.
 * See revision control history for contributions.
 * This file is covered by the LICENSE.md file in the root of this project.
 */

#include <fstream>
#include <sstream>
#include <string>

#include "city_file.h"
#include "elevation_map.h"
#include "site.h"
#include "utilities.h"

void CityFile::LoadCities(const std::string &filename, ElevationMap &em) {
    /* This function reads SPLAT! city/site files, and plots
     the locations and names of the cities and site locations
     read on topographic maps generated by SPLAT! */

    std::string line;
    Site city_site;
    std::stringstream ss;

    std::ifstream infile(filename);

    if (infile.is_open()) {
        fprintf(stdout, "\nReading \"%s\"... ", filename.c_str());
        fflush(stdout);

        while (std::getline(infile, line)) {
            /* Parse line for name, latitude, and longitude */
            // Format: name,latitude,longitude

            size_t first_comma = line.find(',');
            if (first_comma == std::string::npos)
                continue;

            size_t second_comma = line.find(',', first_comma + 1);
            if (second_comma == std::string::npos)
                continue;

            city_site.name = line.substr(0, first_comma);
            std::string lat_str =
                line.substr(first_comma + 1, second_comma - first_comma - 1);
            std::string lon_str = line.substr(second_comma + 1);

            city_site.lat = Utilities::ReadBearing(lat_str);
            city_site.lon = Utilities::ReadBearing(lon_str);
            city_site.alt = 0.0;

            if (city_site.lon < 0.0)
                city_site.lon += 360.0;

            em.PlaceMarker(city_site);
        }

        infile.close();
        fprintf(stdout, "Done!");
        fflush(stdout);
    }

    else
        fprintf(stderr, "\n*** ERROR: \"%s\": not found!", filename.c_str());
}
